### ISSUE TITLE
Vault namespace support

### ISSUE THREAD

**Issue by trodemaster** [joemiller/vault-token-helper#14]
Have you considered adding namespace support to this tool? Instead of keying off only the VAULT_ADDR each record would need to use VAULT_NAMESPACE in addition.

**Comment by trodemaster** [comment]
I took a stab at adding namespace support and seems workable. https://github.com/trodemaster/vault-token-helper/commit/e2c3b6bf1f839283d37fbabfd4ebe0548230cf1e
I can do a pull request if you want to grant me that access?

**Comment by trodemaster** [comment]
I sorted out how to to the pull request and have done so.

**Comment by joemiller** [comment]
@trodemaster I _just_ noticed this issue, terribly sorry :( Must have missed the notification.

If you're still interested this would be a great feature and a PR would be welcomed

**Comment by trodemaster** [comment]
Here is the PR https://github.com/joemiller/vault-token-helper/pull/15 Simplistic change but it has been working well for me.

**Comment by joemiller** [comment]
thanks @trodemaster . v0.3.0 is available in github releases and linux/macos homebrew now

```console
$ vault-token-helper version
0.3.0+f0a87d3
```
