### ISSUE TITLE
Unable to access newly stored token on macOS 10.15+

### ISSUE THREAD

**Issue by trodemaster** [joemiller/vault-token-helper#22]
After completing a vault login the token data is successfully stored in keychain as expected on macOS using the keychain store. However when attempting to access vault using the stored token it will fail. The access control attribute of the secret stored in the keychain is not correct. If you toggle on the "allow all applications to access this item" in the  access control tab it works as expected. 

This is likely an issue with the keyring dependency. A quick look at that repo didn't show any related issues.

**Comment by joemiller** [comment]
I am running macOS 10.15+ but have not run into any issues. Do you mean macOS 11 Big Sur, perhaps? I am not able to upgrade to Big Sur yet.

Do you have any suggestions on how to reproduce and/or fix in the code? Perhaps just a matter of updating the keyring dep? If that's the fix that'd be great but not sure how to verify the fix.

**Comment by trodemaster** [comment]
Let me setup another validation on a clean system to see if it repro again. I was seeing this on 10.15.x and had to update each secret in keychain after it was created to read the key. Updating the key ring dep was what I started to look at but ran out of time.

**Comment by joemiller** [comment]
@trodemaster BTW, I noticed we're both on the #hangOps Slack if you want to chat there.

**Comment by trodemaster** [comment]
Hey I think this can be closed. I suspect this behavior was caused by me running a locally built version of the vault-token-helper that was not signed. I have not been able to reproduce this after using the release binary.
